name: Tests

on:
  repository_dispatch:
    types: [vercel_build]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Dependencies
        run: yarn

      - name: Run Mocha Tests
        run: yarn test
